### ISSUE TITLE
layout.might_permit_raw_init supports additional checks

### ISSUE THREAD

**Issue by tedinski** [model-checking/kani#1273]
Rust's `layout.might_permit_raw_init` went from taking true/false flag to taking:

1. `InitKind::Zero, *` which corresponds to the old `true` (and the intrinsic `assert_zero_valid`)
2. `InitKind::Uninit, false` which corresponds to the old `false` (and the instrinsic `assert_uninit_valid`)
3. `InitKind::Uninit, false` which adds an additional strict check. Unclear if we want it for something.

Upstream PR: https://github.com/rust-lang/rust/pull/97323

**Comment by adpaco-aws** [comment]
In the most recent update, Rust provides two methods `permits_zero_init` and `permits_uninit_init` for the type context (where layout is the argument) instead of the method `might_permit_raw_init` for layouts. 

The updates to the intrinsics code in #1399 make use of them (as in [the `ssa` and `cranelift` backends](https://github.com/rust-lang/rust/pull/99033/files)), so there's nothing else to do here.
