### ISSUE TITLE
Clean up code related to broken --gen-c-runnable

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#1384]
I would like to propose that we clean the code related to the broken `--gen-c-runnable` flag. In fact, we have never enabled this flag in `kani-driver`. Please let me know if anyone has any objection.

**Comment by tedinski** [comment]
When I wrote `kani-driver` I dropped this feature because there were parts of it that were taking me too longer to figure out how to translate correctly (in part because I wasn't sure the python was doing the correct thing in the first place). It's been a TODO ever since, since I had higher priorities...

Obviously nobody has used it in awhile. I don't object.

**Comment by celinval** [comment]
I do remember it being broken before we introduced `kani-driver`. @danielsn what do you think?
