### ISSUE TITLE
#[kani::async_proof] should be merged into #[kani:proof]

### ISSUE THREAD

**Issue by fzaiser** [model-checking/kani#1464]
In https://github.com/model-checking/kani/pull/1430#issuecomment-1204585500, @camshaft suggested that instead of having two different attributes for `async fn` and `fn`, we should just have one attribute `#[kani::proof]`, which would do the right thing depending on whether the function is `async` or not.

Pros: more uniform API

Cons: kani::proof does not take arguments, but kani::async_proof probably will in the future (to select an executor)

I'm leaning towards a separate attribute. What do people think? @model-checking/kani-devs

**Comment by YoshikiTakashima** [comment]
With regard to taking an executor, would it be a configuration? In that case, would it not be similar to how we already put unwind bounds? 

- Case 1: If nothing is provided, we run with the "default" executor. One questions is whether there will be unsoundness b/c user was expecting to use one executor but got another.
- Case 2: refusing to run if at least 1 executor is not provided. Why not allow the users to add as many executors as they want and we test them all?

**Comment by celinval** [comment]
I like @camshaft's suggestion. It's simpler and it's something that we can figure out without too much work.

**Comment by camshaft** [comment]
The existing `kani::proof` attribute can be expanded to also take arguments so I'm not a con here. One thing you have to consider with the two is "what happens when I put `async_proof` on a non-async function? Or put `proof` on an async function? Will the error message be good enough to know what to do? If the macros are smart enough to detect their misuse, then why wouldn't they just do the correct thing in the first place?

**Comment by fzaiser** [comment]
I just discussed with @danielsn, and he also thinks only having `#[kani::proof]` is better. Since everyone seems to agree, I'll prepare a PR this week to change it. Thanks @camshaft!

**Comment by fzaiser** [comment]
PR is up: #1471
