### ISSUE TITLE
Investigate `Vec` performance issues

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#1676]
- [x] https://github.com/model-checking/kani/issues/1657
- [x] https://github.com/model-checking/kani/issues/1673
- [x] https://github.com/model-checking/kani/issues/1226

**Comment by tautschnig** [comment]
https://github.com/diffblue/cbmc/pull/7230 appears to address #1657 and #1673, but I'm not yet entirely sure about #1226 for that one yields unwinding assertion failures (the examples do terminate much quicker than said in that issue, but I cannot say for sure that this isn't because of changes in how unwinding is interpreted, which has happened at some point).

**Comment by tautschnig** [comment]
I have now created a collection of PRs that, together, will address this issue:

- [ ] diffblue/cbmc#7230
- [ ] https://github.com/diffblue/cbmc/pull/7331
- [ ] https://github.com/diffblue/cbmc/pull/7339
- [ ] https://github.com/diffblue/cbmc/pull/7340
- [ ] https://github.com/diffblue/cbmc/pull/7341
- [ ] https://github.com/diffblue/cbmc/pull/7342
- [ ] https://github.com/diffblue/cbmc/pull/7343
- [ ] https://github.com/diffblue/cbmc/pull/7344

**Comment by tautschnig** [comment]
All CBMC PRs are now merged and will be part of the 5.72.0 release (due to be published 2022-12-08).
