### ISSUE TITLE
[Documentation] PATH needs to be set before running regression tests script

### ISSUE THREAD

**Issue by roypat** [model-checking/kani#1776]
When building Kani from source, the [instructions](https://model-checking.github.io/kani/build-from-source.html) tell to `Then, optionally, run the regression tests`. However, this step only works _after_ setting the PATH environment variable to include the Kani scripts folder (which in the instructions only comes after running the regression tests). The order of these two instructions should be inverted to prevent confusion during setup. 

Without first modifying `PATH`, executing Kani will result in the error 

```zsh
Error: Failed to invoke kani-driver

Caused by:
    No such file or directory (os error 2)
```

**Comment by adpaco-aws** [comment]
Thanks for the bug report, @roypat !

I've just tried following the steps you describe and running the regression script worked for me without adding Kani to `PATH`. Can you please try again and confirm it works on your end?

**Comment by tedinski** [comment]
`kani-regression.sh` does contain the line: `export PATH=$SCRIPT_DIR:$PATH`

I think this might be a different issue: Possibly you had `kani` or `cargo-kani` in `~/.cargo/bin` from a previous attempt to install kani by that method, and this failed and left itself in a partially installed state or something. In that case this would be somewhat similar to #1545

So on the one hand we should fix the "partially installed state" problem, but perhaps we should also fix the issue here where we might be running global kani binaries somehow from our regression scripts instead of the local ones built in the repo.

**Comment by roypat** [comment]
> `kani-regression.sh` does contain the line: `export PATH=$SCRIPT_DIR:$PATH`
> 
> I think this might be a different issue: Possibly you had `kani` or `cargo-kani` in `~/.cargo/bin` from a previous attempt to install kani by that method, and this failed and left itself in a partially installed state or something. In that case this would be somewhat similar to #1545
> 
> So on the one hand we should fix the "partially installed state" problem, but perhaps we should also fix the issue here where we might be running global kani binaries somehow from our regression scripts instead of the local ones built in the repo.

Sorry for not getting back to you earlier! Yes, I think you are right, I remember messing around with my `PATH` for some reason. I cannot replicate this anymore (just tried a clean install of kani)!
