### ISSUE TITLE
Create rational set of labels

### ISSUE THREAD

**Issue by danielsn** [model-checking/kani#1867]
We currently have 57 labels and a bunch of duplicates. We should clean them.

**Comment by celinval** [comment]
Here is a proposal:

Every issue has to be tagged with one Category and one Sub-Category. 

## Category

These are the categories are

| Label | Description
| -- | --
[C] Bug | This is a bug. Kani is misbehaving.
[C] Feature | A new feature request
[C] Enhancement | An issue or PR that proposes an enhancement to an existing feature.
[C] Internal | Tracks some internal work

## Sub-category

For each category, we have a set of sub-category.

Type of Failure:
| Label | Description
| -- | --
[F] Crash | Kani crashed
[F] Spurious CEX | Kani detected a failure that doesn’t exist
[F] Soundness | Kani failed to detect an issue
[F] Hang | Kani seems to be hanging

Type of enhancement:

| Label | Description
| -- | --
[E] Performance | Task to improve Kani’s performance
[E] Deprecation | Track the deprecation of an existing feature.
[E] User Experience | A UX enhancement for an existing feature

Type of internal work:
| Label | Description
| -- | --
[I] CI | CI related tasks
[I] Tests | Add / Remove / Improve tests
[I] Design | Designing and planning tasks
[I] Refactoring | Refactoring of existing code
[I] CleanUp | Cleanup existing code

For feature, any suggestions??

## Tags
Additionally, we may also create tags to make it easier for us to join issues. I suggested that we start with the following tags:

Tags for priorities:
| Label | Description
| -- | --
P-High |  
P-Medium |  
P-Low |  

Random tags:
| Label | Description
| -- | --
T-RFC | Label RFC PRs and Issues
T-User | Tag user issues / requests

**Comment by tedinski** [comment]
As a "constraint proposal" I think we should aim to have an easily-selected set of labels. On my screen right now, I can see 11 labels (if they have no descriptions, 7 otherwise). Not sure if that's consistent between browsers or whatever. I'd propose we have either that many only or 2x that (so "flick scroll wheel" is all that's needed to see the rest, without any effort needed to either carefully scroll through the list or type to search for a particular label). So, 7, 11, 14, or 22 labels max, depending. (This proposal does have 22!)

I'll also say I'm skeptical of lots of categories/etc. Classifying everything perfectly along several dimensions is something that in my experience seems like it should be great but also means people just don't use it. (Not just in that people don't bother tagging: also the other way around. Nobody looks at things tagged "whatever" so why bother?)

So here's a few ideas on radically reducing label counts to try to fit my preferences, to make the idea more concrete:

* IMO no useful distinction between "feature" or "enhancement".
* I think we'd skip "subcategories" entirely except maybe for bugs.
* So instead of "internal + subcategory" I'd probably just have two: "ci / tests (maybe a better name)" and "cleanup / refactor (maybe just cleanup?)"
* priorities other than "high" can generally just be omitted entirely.

Let me count what that would leave:

1. bug
2. feature
3. ci / tests
4. cleanup
5. High Priority
6. RFC
7. User Impact
8. Crash
9. False Positive
10. Soundness
11. Performance

Ah! This would mean one page of labels, making it a lot easier to tag things. Like I said, I think 22 would be ok, but would leave no room for adding more. Assuming we accepted my size constraints here :)

**Comment by celinval** [comment]
Updated proposal:

## Category

Each category would map to one template. They are added when someone creates a new issue:

| Label | Description
| -- | --
[C] Bug | This is a bug. Kani is misbehaving.
[C] Feature | A new feature request or enhancement to an existing feature.
[C] Internal | Tracks some internal work

## Sub-category

For each category, we have a set of sub-category. These labels should be added as part of the triage process.

Type of Failure:
| Label | Description
| -- | --
[F] Crash | Kani crashed
[F] Spurious CEX | Kani detected a failure that doesn’t exist
[F] Soundness | Kani failed to detect an issue
[F] Hang | Kani seems to be hanging

Type of enhancement:

| Label | Description
| -- | --
[E] Performance | Task to improve Kani’s performance
[E] User Experience | An UX enhancement for an existing feature. Including deprecation of an existing one.
[E] New Feature | The request for a feature that is not currently supported.

Type of internal work:
| Label | Description
| -- | --
[I] CI / Infrastructure | Work done to CI, tests and infrastructure.
[I] Refactoring / Clean Up | Refactoring or cleaning up of existing code


## Tags

Additionally, we may also create tags to make it easier for us to join issues. I suggested that we start with the following tags:

Random tags:
| Label | Description
| -- | --
T-RFC | Label RFC PRs and Issues
T-User | Tag user issues / requests
T-High Priority | Tag issues that have high priority

Question, what about "good first issue"? I think they are used to populate this table: https://github.com/model-checking/kani/contribute

**Comment by celinval** [comment]
This has been reviewed and changes have been applied to our existing labels. Now I just need to update the templates.
