### ISSUE TITLE
Slow down and higher memory usage with 2023-04-30 rust toolchain

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#2457]
With the 2023-04-30 rust toolchain, performance drops significantly on the `BTreeSet` performance regressions.

For example, with the current main (08659d303e8bd1c36add7d42951c52b5e9546c38), the verification time for `tests/perf/btreeset/insert_any` is 1.5 seconds:
```
SUMMARY:
 ** 0 of 1301 failed (60 unreachable)

VERIFICATION:- SUCCESSFUL
Verification Time: 1.4937471s
```
With https://github.com/model-checking/kani/pull/2456, the verification time goes up to 141 seconds:
```
SUMMARY:
 ** 0 of 1306 failed (60 unreachable)

VERIFICATION:- SUCCESSFUL
Verification Time: 141.20958s
```

For `tests/perf/btreeset/insert_multi`, the peak memory usage with main is ~600 MB and verification time is 10 seconds:
```
SUMMARY:
 ** 0 of 1241 failed (46 unreachable)

 ** 2 of 2 cover properties satisfied


VERIFICATION:- SUCCESSFUL
Verification Time: 10.019767s
```
With #2456, CBMC runs out of memory (reaches ~26 GB after about 16 minutes).

Similar behavior is observed for `tests/perf/btreeset/insert_same`.

**Comment by zhassan-aws** [comment]
These are some of the CBMC statistics on the `insert_any` example:
![image](https://github.com/model-checking/kani/assets/88045115/d2dcfc53-345b-43b7-ac4c-512a07a842c4)

**Comment by tautschnig** [comment]
It seems that the updated toolchain does even more niche optimisation, turning a further tagged union into a niche-optimised one (with the two union members using slightly different member ordering so that a pointer can be used as discriminant (when set to NULL)). https://github.com/diffblue/cbmc/pull/7739 enables CBMC to cope with this case, making sure that field sensitivity can kick in to resolve a comparison against NULL at symbolic execution time.
