### ISSUE TITLE
Publish documentation for library component (e.g. `kani::any()` et al) to docs.rs

### ISSUE THREAD

**Issue by roypat** [model-checking/kani#2627]
**Requested feature:** It'd be nice to be able to look up what functions for creating non-deterministic values kani offers on doc.rs. Currently, the `kani-verifier` binary crate has its documentation published, which does not contain documentation for the functions actually used by proofs (https://docs.rs/releases/search?query=kani). Those are contained in https://github.com/model-checking/kani/tree/main/library/kani, which even contains a few (very useful!) functions that are no mentioned in the tutorial (like `any_vec`). 

**Use case:** Easily discover the APIs kani offers. 

**Link to relevant documentation (Rust reference, Nomicon, RFC):** None yet, but can be generated by running `cargo doc` inside of `library/kani`.

**Comment by adpaco-aws** [comment]
Hi @roypat, thanks for your request!

Do you have a preference for this documentation to be in [docs.rs](https://docs.rs/) or you just want it to be somewhere?

Asking because we were planning on adding the Kani APIs to our reference section in the documentation, similar to [what we've done for Kani attributes](https://model-checking.github.io/kani/reference/attributes.html) (couldn't find the issue for that). If I'm not mistaken, adding the documentation to [docs.rs](https://docs.rs/) would require us to publish the Kani library crate.

**Comment by roypat** [comment]
Heyo, thanks for getting back so quickly! I don't have any preference on the location really, I guess it was less of a request for doc.rs specifically and more of a request for "rustdoc style" docs somewhere, as that's the canonical documentation format for rust things :P Just looking at the output of `cargo doc`, it does include all the attributes, but it seems the contents of the doc-comments and the link you gave are different. Maybe that could be unified as part of this?

**Comment by celinval** [comment]
We also publish that here: https://model-checking.github.io/kani/crates/doc/kani/

**Comment by JustusAdam** [comment]
> @roypat Is this what you are looking for? https://model-checking.github.io/kani/crates/doc/kani/

How about we add a link to that on the crate documentation for `kani-verifier` and the `kani` placeholder?

**Comment by roypat** [comment]
> @roypat Is this what you are looking for? https://model-checking.github.io/kani/crates/doc/kani/

That is indeed what I was looking for!! So sorry for not finding that myself >.>
