### ISSUE TITLE
Understanding kani's output

### ISSUE THREAD

**Issue by 0xAtticus** [model-checking/kani#3096]
Hello,

Sorry this is not really a feature request, but I could not find any community place where I  could ask this question (so maybe I am requesting the feature to have such a space ?)

I do have the following very simple test case: 
```rust
#[cfg(kani)]
#[kani::proof]
fn hmm() {
    let v: Vec<u8> = vec![1; 0];
}
```

That, surprisingly fails (at least surprisingly for me).
```
SUMMARY:
 ** 1 of 137 failed (4 unreachable)
Failed Checks: memset destination region writeable
 File: "/github/home/.rustup/toolchains/nightly-2024-03-11-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs", line 3162, in std::intrinsics::write_bytes::<u8>
 ```

But using the `concrete-playback` option, then using the `playback` command, everything works.
And I admit I have trouble navigating through the output provided by `cargo kani --visualize --enable-unstable`.

Is there any documentation that could teach me how to properly read and understand the output of `kani` with the `--visualize` argument.

Or if you have any idea of why this test could fail, I would love to know it too. 

Thank you very much !

**Comment by zhassan-aws** [comment]
Hi @0xAtticus. Thanks for opening this issue. Opening an issue is the best way to ask a question at the moment :)

This is a known bug in Kani (see https://github.com/model-checking/kani/issues/90): the failure is spurious and is likely due to the usage of a dangling pointer in the vector implementation.

Concrete playback along with your favorite debugger (e.g. lldb) is the recommended approach for debugging traces. In this case, there's nothing to debug because the failure Kani reports is incorrect.

The `--visualize` option is deprecated, and will likely be removed in the future.

**Comment by 0xAtticus** [comment]
Very clear, thank you very much !
