### ISSUE TITLE
Point-to-analysis fail if an instance does not have a body

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#3447]
I tried this code:

```rust
#[kani::proof]
fn check_sz() {
    let refstr = "hello";
    let ptr = refstr as *const _;
    assert_eq!(size_of_val(&ptr), 4);
}
```

using the following command line invocation:

```
kani check_sz.rs -Z uninit-checks
```

with Kani version:

I expected to see this happen: Verification succeeds

Instead, this happened: Kani crashes

```
Kani Rust Verifier 0.54.0 (standalone)
thread 'rustc' panicked at kani-compiler/src/kani_middle/points_to/points_to_analysis.rs:449:54:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Kani unexpectedly panicked during compilation.
Please file an issue here: https://github.com/model-checking/kani/issues/new?labels=bug&template=bug_report.md

[Kani] no current codegen item.
[Kani] no current codegen location.

```

**Comment by artemagvanian** [comment]
That's weird. It seems like the error is caused by following this `if` branch:
https://github.com/model-checking/kani/blob/e6f8a62d689d0b0ebcbabe3661be6273c5ab9be8/kani-compiler/src/kani_middle/points_to/points_to_analysis.rs#L208-L210

However, we later fail to obtain the actual body for the intrinsic here:
https://github.com/model-checking/kani/blob/e6f8a62d689d0b0ebcbabe3661be6273c5ab9be8/kani-compiler/src/kani_middle/points_to/points_to_analysis.rs#L446-L450

I think we should be getting the body via `instance_mir` instead of jumping into StableMIR and back.

**Comment by celinval** [comment]
I believe the problem here is that `is_mir_available` is not sufficient since you also need to check if the intrinsic has to be overwritten.

StableMIR already includes both checks.

**Comment by celinval** [comment]
See https://github.com/rust-lang/rust/blob/4fe1e2bd5bf5a6f1cb245f161a5e9d315766f103/compiler/rustc_smir/src/rustc_smir/mod.rs#L74-L81

**Comment by artemagvanian** [comment]
Thanks! That's good to know. It turned out I only had to add support for 3 intrinsics to get rid of `is_mir_available` check altogether.
