### ISSUE TITLE
RMC should use fully qualified name for harness selection and it should not rely on `no_mangle` attribute

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#661]
Users should be able to use RMC to target functions with the same name in different modules. For example, if user wants to verify the following code:

```rust
mod first {
    fn check() {
        // some check
    }
}

mod second {
    fn check() {
        // check for second module
    }
}

pub fn check() {
  // full check
}
```

They should be able to provide which function they want to check. I.e:
```
rmc multiple.rs --function [check | first::check | second::check]
```

Note that users cannot use `#[no_mangle]` for the check functions, since this would cause a name conflict. The compilation would fail with the following error:
```
error: symbol `check` is already defined
  --> multiple.rs:26:1
   |
26 | fn check() {
   | ^^^^^^^^^^^^^^

error: aborting due to previous error

```

**Comment by tedinski** [comment]
1. Proof annotations should solve this, as we get a mapping in `rmc-metadata.json` from pretty names to mangled names. So when `cargo-rmc` exists and is looking at this mapping, we can easily find the function to use.
2. But right now proof annotations are using `no_mangle` as a hack in order to force codegen of the function. We need an alternative solution to this problem.

So far the only options I've come up with are:

1. Instead of putting `#[no_mangle]` in the case of `cfg(rmc)`, we could put `#[test]` and always have rmc build in "test mode" (i.e. `cargo test --no-run` not `cargo build`). One thing 'test' does is make the function get codegen'd, and that's all we need from it. This does have the advantage of being completely reliable.
2. We could see if `#[export_name = concat!(module_path!(), "::", #test_name))]` works and so generate fully qualified names ourselves. Might not be as reliable as Rust's native name mangling though.

**Comment by tedinski** [comment]
Current status:

* We can run proof harnesses by short and full name.
* We **have not yet** removed `no_mangle` as we haven't picked a way to ensure Rust codegen's each function.

**Comment by celinval** [comment]
This should work with the new MIR Linker. But we still need to remove the legacy one in order to remove it.

**Comment by YoshikiTakashima** [comment]
@celinval, @tedinski this is blocking a 10/29 when evaluating proptest project. What is the remaining todos?

**Comment by tedinski** [comment]
I'm not sure. I think it might work with `no_mangle` removed now, and the only reason we haven't is the lingering need to support the legacy linker...

**Comment by YoshikiTakashima** [comment]
P.S. I implemented @tedinski 's Option 2 (` #[export_name = concat!(module_path!(), "::", #test_name))]`) and I don't see major breakage so I would go with that.
